services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: "app-de-doze-fatores"
    ports:
      - ${PORT}:8080
    env_file:
      - .env
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

